name: Continuous Integration & Test Report

on:
  push:
    branches:
      - "Wzrd/unit-test"
      - "development"

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      - name: Install dependencies
        run: flutter pub get

      - name: Upgrade dependencies
        run: flutter pub upgrade

      - name: Run & Generate Test Coverage report
        run: flutter test --coverage --machine > coverage.json
      - uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.json
          slug: W-zrd/unishare_mobile
        continue-on-error: true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Flutter Unit Test
          path: reports/test-*.json
          reporter: flutter-json
